version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    working_dir: '/usr/src/app'
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./models:/usr/src/app/models
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ./models:/usr/src/app/models
      - ./graphs:/usr/src/app/graphs
