FROM node:14 AS node-build
WORKDIR /src
COPY js js
COPY static static
COPY webpack.config.js package.json ./
RUN npm install
RUN npm run build

FROM python:3.7
WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src src
RUN cd src && python setup.py build_ext --inplace

COPY --from=node-build /src/dist dist

CMD python src/server.py