FROM python:3.7
WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY requirements.txt .
COPY requirements_train.txt .
RUN pip install --no-cache-dir -r requirements_train.txt

COPY src src
RUN cd src && python setup.py build_ext --inplace

CMD python src/eval_obs.py