#!/bin/bash
set -eu
cd `dirname $0`
docker tag gameai-app 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-app:$DOCKER_TAG
docker tag gameai-app 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-app:latest
docker push 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-app:$DOCKER_TAG
docker push 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-app:latest
docker tag gameai-nginx 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-nginx:$DOCKER_TAG
docker tag gameai-nginx 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-nginx:latest
docker push 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-nginx:$DOCKER_TAG
docker push 554746007656.dkr.ecr.ap-northeast-1.amazonaws.com/gameai-nginx:latest